### ISSUE TITLE
Design issue

### ISSUE THREAD

**Issue by antho1404** [mesg-foundation/aragon#13]
Seems like the table has a size issue

<img width="1257" alt="Screen Shot 2020-05-06 at 11 26 14" src="https://user-images.githubusercontent.com/1783126/81138493-72a79480-8f8c-11ea-9203-420a1622f196.png">

**Comment by blackinno** [comment]
@antho1404 This issue is coming from data of the previous version and I use the @aragon-ui library and I didn't custom any CSS from the @aragon-ui library and is work correctly with the new publish [Link](https://rinkeby.aragon.org/#/0x702E819000FC3Be0dadC99480401bD94DBD5b322/0xf390905ab56bf9ed27fbc9d24ead1b46c8053ec5/)

**Comment by blackinno** [comment]
Done.
